<<<<<<< HEAD
##trying to make cleaner.py and tessarac work
=======
>>>>>>> b6bf284 (using docker in fastapi)
services:
  - type: web
    name: ai-invoice-api-service
    env: python
    buildCommand: |
      cd api-service
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: |
      cd api-service
      uvicorn main:app --host 0.0.0.0 --port $PORT
